### ISSUE TITLE
Update display fields in search data

### ISSUE THREAD

**Issue by malakyeshort** [WebDevJBR/volunteer-points-log#150]
User Portal >> Search Page
The totals for Actual Hours, Earned Hours, available Feathers, and available Above and Beyond should be added to the information displayed when a search is ran.

**Comment by lukesample** [comment]
@malakyeshort is this referring to each volunteer card in the list? i.e. each one of these entries should display the fields mentioned in the ticket?

![image](https://user-images.githubusercontent.com/38770659/127415350-8d4b39bf-88eb-44a3-ad76-a08fb8f6d0e7.png)

**Comment by malakyeshort** [comment]
@lukesample correct. Each volunteer card should display the information listed for that volunteer.
