### ISSUE TITLE
Display error messages without clearing entered data

### ISSUE THREAD

**Issue by malakyeshort** [WebDevJBR/volunteer-points-log#160]
User Portal >> Log Hours page
Currently if a new time entry is filled out and an error is thrown (times overlap for example) the entered data is lost and the user has to enter it again. If possible, we would like the data to remain in the fields so the user can fix the error and submit.

**Comment by johnnylofton** [comment]
Will need confirmation but I think the constraints on the data that throw the error will not allow us to save it despite it.
