### ISSUE TITLE
User Search List

### ISSUE THREAD

**Issue by brandonavant** [WebDevJBR/volunteer-points-log#29]
## Description

As a user, I should be presented with search results that result from entering information into the search bar in the Navigation Bar (#23).

## Acceptance Criteria

- For now, the image should simply be a static image with supporting updating the image in the future in mind.
- As outlined in the wireframe, the following fields should be shown:
    - Name
    - MKA
    - Info Missing Note: This only appears IFF the corresponding flag is set for this record in the database.
    - Membership #
- Clicking the *Edit* button should bring up the *Edit Volunteer* screen (#24 ).
- Clicking the *Hours* button should bring up the *Edit Volunteer Hours* screen (#30 ).
- The search box should be scrollable.
- Scrolling should not affect the position of the navigation bar; it should be stationary.

**Comment by mharris4** [comment]
Using existing closed story to finish out the volunteer search page
