### ISSUE TITLE
Implement ApiService

### ISSUE THREAD

**Issue by brandonavant** [WebDevJBR/volunteer-points-log#33]
As an architect, I need to ensure that developers have a reliable means by which they can perform HTTP operations in a way that provides continuous feedback.

**Comment by Feorice** [comment]
I noticed this is in the "Review in Progress" lane on the Kanban board. Should this just be in the "In Progress" lane instead?

**Comment by brandonavant** [comment]
> I noticed this is in the "Review in Progress" lane on the Kanban board. Should this just be in the "In Progress" lane instead?

No, it should be in done. I just moved it.
