### ISSUE TITLE
Use isNaN to check for value number when using parseInt

### ISSUE THREAD

**Issue by brandonavant** [WebDevJBR/volunteer-points-log#41]
In UserLogin, parseInt is being used without performing an isNaN() check prior to attempting to use the parsed value. If for some reason an invalid value is passed in and parsed, attempting to use 'id' with the assumption that it's in fact a Number will throw an error. Consider writing code that will allow for us to gracefully recover.

**Comment by Feorice** [comment]
This was fixed in ISSUE #14. It has not been merged yet.
